### ISSUE TITLE
Export Components as material-ui

### ISSUE THREAD

**Issue by rgnevashev** [fermuch/simple-react-form-bootstrap#1]
could you make export components like simple-react-form-material-ui?
`<Field type="string">` is deprecated.

**Comment by fermuch** [comment]
Yes, I'll work on it on the weekend.
Basically we would only need to update the index and add an export to each Field.

Some updating & love is also needed for implementing new features and updating the code to match the latest version of SRF :)

**Comment by rgnevashev** [comment]
thank you very much! looking forward new style Field Components :)

**Comment by fermuch** [comment]
Better late than never :)

I rewrote every component so you can import it like:

```
import {TextField} from 'simple-react-form-bootstrap/lib/fields/string';
```

I didn't document what everything is exporting (yet) but I released the version `0.1.0` so you can use it.
If you need to see what everything exports, check out the bottom of the files. 
For example, the file `select.jsx`:

```
export {
  SelectFieldComponent as SelectField
};
```

I also updated the [example](https://github.com/fermuch/simple-react-form-bootstrap-examples).

If you're using it, or are trying it for the first time, I'd really appreciate some feedback to know where I could improve the code.

**Comment by rgnevashev** [comment]
https://github.com/nicolaslopezj/simple-react-form-material-ui/blob/master/src/index.js
I think this package should be able follow:
`import {Text, Select} from 'simple-react-form-bootstrap'`
like done in material UI

**Comment by rgnevashev** [comment]
one notice
`<Field fieldName="test">` generate input with html code:
`<input type="string" ...>`
I think by default type prop should be "text"

**Comment by fermuch** [comment]
Done and done. I'm closing this issue now.
Feel free to open a new one if you notice something else :smile:

**Comment by rgnevashev** [comment]
Now by default all inputs becomes how textarea.. It shoulld be `<input type="text">` by default .. not textarea

**Comment by rgnevashev** [comment]
```
import { TextField as Text } from 'simple-react-form-bootstrap'
<Field fieldName="firstName" type={Text} label="First Name" />
```

become `<textarea>` but should be `<input type="text">`

**Comment by fermuch** [comment]
That's not happening to me. Let me test a little bit what could be the problem.

**Comment by fermuch** [comment]
Okay, now version `0.3.0` fixes this. I added a new `TextareaField` for textareas.

**Comment by rgnevashev** [comment]
Thank you very much! I would like to offer you a new component for the textarea but you have already done this component )

**Comment by fermuch** [comment]
Glad it's finally solved!
I'm open to new components or rewrites, if there's a use case. Is yours using react-bootstrap? Does it bring something else `TextareaField` doesn't?
