### ISSUE TITLE
Replace this.passProps to this.props.passProps

### ISSUE THREAD

**Issue by rgnevashev** [fermuch/simple-react-form-bootstrap#6]

**Comment by rgnevashev** [comment]
https://github.com/fermuch/simple-react-form-bootstrap/blob/master/src/fields/string.js#L56
There is a bug on that line

**Comment by fermuch** [comment]
Oh, sorry, didn't see this one. I assume this one comes from the moving from the classes' parent.

If you make a PR, I'll merge it in no time, but right now I don't think I'll be able to make this change.

**Comment by rgnevashev** [comment]
Done. See https://github.com/fermuch/simple-react-form-bootstrap/pull/7 for fix

**Comment by fermuch** [comment]
Done! Thanks! It's available in version `0.6.2`.
